#!/usr/bin/env bash
set -e;
VOLUME=100;
TIME=$2;
MUSIC_PATH=$1;

if [ $(date +%s --date="$TIME") -lt $(date +%s --date="now") ]
then
   echo -n "Tomorrow at "
   RTC_DATE=$(date +%s --date="tomorrow $TIME")
elif [ 1 ]
then
   echo -n "Today at "
   RTC_DATE=$(date +%s --date="$TIME")
fi

echo "$TIME";
echo "Volume: $VOLUME Music-Path: $MUSIC_PATH";

sudo rtcwake -u -m no -t $RTC_DATE;
echo "export DISPLAY=$DISPLAY; mpv --no-video --no-terminal --no-audio-display --volume=$VOLUME '$MUSIC_PATH'" | at -M "$TIME" + 1 minute;

