#!/usr/bin/env bash
set -e;
VOLUME=100;
TIME=$2;
MUSIC_PATH="$1";
MPV="mpv"
MPV_FLAGS="--no-video \
   --no-terminal \
   --no-audio-display \
   --volume=${VOLUME} \
   --input-unix-socket=/tmp/mpv.socket"

if [ $(date +%s --date="$TIME") -lt $(date +%s --date="now") ]
then
   echo -n "Tomorrow at ";
   RTC_DATE=$(date +%s --date="tomorrow $TIME");
else
   echo -n "Today at ";
   RTC_DATE=$(date +%s --date="$TIME");
fi

echo "$TIME";
echo "Volume: $VOLUME Music-Path: $MUSIC_PATH";

sudo rtcwake -u -m no -t $RTC_DATE;
echo "export DISPLAY=$DISPLAY; $MPV $MPV_FLAGS -- $MUSIC_PATH" | at -M "$TIME" + 1 minutes;

